<?php
echo "<!DOCTYPE html>";
echo "<html lang='en'>";
echo "<head>";
echo "  <meta charset='UTF-8'>";
echo "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
echo "  <link rel='stylesheet' type='text/css' href='render/renderstyles.css'>";
echo "  <meta http-equiv='X-UA-Compatible' content='ie=edge'>";
echo "    <!-- insert firebase JS dependency nightmare -->";
echo "";
echo "    <!-- Insert these scripts at the bottom of the HTML, but before you use any Firebase services -->";
echo "";
echo "    <!-- Firebase App (the core Firebase SDK) is always required and must be listed first -->";
echo "    <script src='https://www.gstatic.com/firebasejs/7.15.5/firebase-app.js'></script>";
echo "";
echo "    <!-- If you enabled Analytics in your project, add the Firebase SDK for Analytics -->";
echo "    <script src='https://www.gstatic.com/firebasejs/7.15.5/firebase-analytics.js'></script>";
echo "";
echo "    <!-- Add Firebase products that you want to use -->";
echo "    <script src='https://www.gstatic.com/firebasejs/7.15.5/firebase-auth.js'></script>";
echo "    <script src='https://www.gstatic.com/firebasejs/7.15.5/firebase-firestore.js'></script>";
echo "    <script src='https://www.gstatic.com/firebasejs/7.15.5/firebase-database.js'></script>";
echo "    <script>";
echo "      var user;";
echo "      // Firebase project configuration";
echo "      const firebaseConfig = {";
echo "        apiKey: 'AIzaSyBeBJKFqfcsZS6WfJIRfAH_D6qZOsBAxh0',";
echo "        authDomain: 'signr-1ab26.firebaseapp.com',";
echo "        databaseURL: 'https://signr-1ab26.firebaseio.com',";
echo "        projectId: 'signr-1ab26',";
echo "        storageBucket: 'signr-1ab26.appspot.com',";
echo "        messagingSenderId: '228825433332',";
echo "        appId: '1:228825433332:web:0f1b1e68df238130240aa1',";
echo "        measurementId: 'G-PKGWK74L07'";
echo "      };";
echo "      // Initialize Firebase";
echo "      firebase.initializeApp(firebaseConfig);";
echo "      firebase.analytics();";
echo "";
echo "    </script>";
echo "";
echo "";
echo "<script type='text/javascript'>";
echo "  initApp = function() {";
echo "    firebase.auth().onAuthStateChanged(function(user) {";
echo "";
echo "      if (user) {";
echo "        // User is signed in.";
echo "        var displayName = user.displayName;";
echo "        var email = user.email;";
echo "        var emailVerified = user.emailVerified;";
echo "        var photoURL = user.photoURL;";
echo "        var uid = user.uid;";
echo "        var phoneNumber = user.phoneNumber;";
echo "        var providerData = user.providerData;";
echo "";
echo "        acct = {";
echo "            displayName: displayName,";
echo "            email: email,";
echo "            emailVerified: emailVerified,";
echo "            phoneNumber: phoneNumber,";
echo "            photoURL: photoURL,";
echo "            uid: uid,";
echo "            providerData: providerData";
echo "        }";
echo "        // console.log(JSON.stringify(acct));";
echo "";
echo "        document.getElementById('name').value = acct.displayName;";
echo "";
echo "";
echo "        user.getIdToken().then(function(accessToken) {";
echo "          // document.getElementById('sign-in-status').textContent = 'Signed in';";
echo "          // document.getElementById('sign-in').textContent = 'Sign out';";
echo "          // document.getElementById('account-details').textContent = JSON.stringify({";
echo "          //   displayName: displayName,";
echo "          //   email: email,";
echo "          //   emailVerified: emailVerified,";
echo "          //   phoneNumber: phoneNumber,";
echo "          //   photoURL: photoURL,";
echo "          //   uid: uid,";
echo "          //   accessToken: accessToken,";
echo "          //   providerData: providerData";
echo "          // }, null, '  ');";
echo "        });";
echo "      } else {";
echo "        // User is signed out.";
echo "        console.log('signed out');";
echo "        var url = new URL(window.location);";
echo "        console.log(window.location);";
echo "        // document.getElementById('sign-in-status').textContent = 'Signed out';";
echo "        // document.getElementById('sign-in').textContent = 'Sign in';";
echo "        // window.location = 'index.html';";
echo "        // document.getElementById('account-details').textContent = 'null';";
echo "      }";
echo "    }, function(error) {";
echo "      console.log(error);";
echo "    });";
echo "  };";
echo "";
echo "  window.addEventListener('load', function() {";
echo "    initApp();";
echo "  });";
echo "</script>";
echo "";
echo "<script>";
echo "  function signout(){";
echo "    firebase.auth().signOut().then(function() {";
echo "      console.log('Signed Out');";
echo "      window.alert('Goodbye, come again soon!' + JSON.stringify(acct));";
echo "      window.location = 'index.html';";
echo "    }, function(error) {";
echo "      console.error('Sign Out Error', error);";
echo "      window.alert('Error signing out!' + error);";
echo "    });";
echo "  }";
echo "</script>";
echo "";
echo "<script src='saver.js'></script>";
echo "<link type='text/css' rel='stylesheet' href='styles/ui.css' />";
echo "";
echo "  <title>Draft</title>";
echo "</head>";
echo "";
echo "";
echo "<body onload=''>";
echo "    <!-- <div id='sign-in-status' style='height: 0px; visibility: hidden;'></div>";
echo "    <div id='sign-in' style='height: 0px; visibility: hidden;'></div>";
echo "    <pre id='account-details' style='height: 0px; visibility: hidden;'></pre> -->";
echo "";
echo "  <div style='margin: 15px;'>";
echo "    <button onclick='signout()' style='float: left;' class='error'>Sign out</button>";
echo "";
// echo "    <input type='text' style='float: right;' placeholder='User Code' id='host_code' value='.$_GET['name'].'>";
echo "  </div>";
echo "  <div style = 'widows: 100%; height: 40px; margin: 15px;'></div>";
echo "";
echo "  <div style='margin: 15px;'>";
echo "    <form method='GET'  action='render/render.html' onformchange='this.form.submit()' target='render_window' >";
echo "      <!-- Message -->";
echo "      <label for='message' >Message:</label>";
echo "      <input type='text' id='message' name='message' onkeyup='formchanged()' class='text-input'><br><br>";
echo "      <!-- Name -->";
echo "      <label for='name'>Name:</label>";
echo "      <input type='text' id='name' name='name' onkeyup='formchanged()' class='text-input'><br><br>";
echo "";
echo "      <!-- Font Buttons -->";
echo "      <!-- sans -->";
echo "      <input type='radio' id='sans' name='font' value='sans' onmouseup='radiochanged('sans')'>";
echo "      <label class='sans' for='sans' onmouseup='radiochanged('sans')'> Sans-Serif</label><br>";
echo "";
echo "      <!-- serif -->";
echo "      <input type='radio' id='serif' name='font' value='serif'  onmouseup='radiochanged('serif')' checked>";
echo "      <label class='serif' for='serif' onmouseup='radiochanged('serif')' >Serif</label><br>";
echo "";
echo "      <!-- mono -->";
echo "      <input type='radio' id='mono' name='font' value='mono' onmouseup='radiochanged('mono')'>";
echo "      <label class='mono' for='mono' onmouseup='radiochanged('mono')'> Monospace</label><br>";
echo "";
echo "      <input type='radio' id='scrawl' name='font' value='scrawl' onmouseup='radiochanged('scrawl')'>";
echo "      <label class='scrawl' for='scrawl' onmouseup='radiochanged('scrawl')'> Scrawl</label><br>";
echo "      <br>";
echo "";
echo "";
echo "      <input type='submit' value='Submit' onclick='save()' class='button good'>";
echo "";
echo "    </form>";
echo "  </div>";
echo "<p>Message Preview:</p>";
echo "  <iframe name='render_window' id='render_window' src='render/render.html?message=[Message]&name=[name]&font=serif' width='100%' height='300' class='message'>";
echo "  </iframe>";
echo "";
echo "    <script>";
echo "      //this script handles the changes in the form for the 'live updates uwu'";
echo "      function radiochanged(radioName){";
echo "        document.getElementById(radioName).checked = true";
echo "        var font = getRadiochecked('font');";
echo "        var message = document.getElementById('message').value;";
echo "        var name = document.getElementById('name').value;";
echo "";
echo "";
echo "        var key= 'font='+font + '&message='+message + '&name='+name;";
echo "";
echo "        updateIframe('render/render.html?' + key);";
echo "      }";
echo "";
echo "      function formchanged(){";
echo "        var font = getRadiochecked('font');";
echo "        var message = document.getElementById('message').value;";
echo "        var name = document.getElementById('name').value;";
echo "";
echo "";
echo "        var key= 'font='+font + '&message='+message + '&name='+name;";
echo "";
echo "        updateIframe('render/render.html?' + key);";
echo "      }";
echo "      function updateIframe(newSrc){";
echo "        document.getElementById('render_window').src = newSrc";
echo "      }";
echo "";
echo "      function getRadiochecked(groupname){";
echo "          var radios = document.getElementsByName(groupname);";
echo "";
echo "          for (var i = 0, length = radios.length; i < length; i++) {";
echo "          if (radios[i].checked) {";
echo "              // return checked radio";
echo "              return (radios[i].value);";
echo "";
echo "              // only one radio can be logically checked, don't check the rest";
echo "          }";
echo "          }";
echo "      }";
echo "    </script>";
echo "";
echo "";
echo "";
echo "";
echo "";
echo "";
echo "";
echo "";
echo "</body>";
echo "";
echo "";
echo "</html>";
?>